app = "folks-mvp"

[build]

[env]
  NODE_ENV = "production"
  PUBLIC_API_MOCKING = "enabled"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
