name: flyDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkoutRepo
        uses: actions/checkout@v4

      - name: setUpFlyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: deployToFly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
